export const pageStyles = {
  root: "flex flex-col gap-6",
  headerWrapper: "flex flex-col lg:flex-row lg:flex-wrap lg:items-end justify-between gap-4",
  headerSpace: "space-y-2",
  nav: "flex items-center gap-2 text-xs font-medium text-text-secondary/60",
  homeIcon: "hover:text-primary transition-colors flex items-center gap-1",
  breadcrumbItem: "flex items-center gap-2",
  separator: "opacity-40",
  titleWrapper: "space-y-1",
  title: "text-3xl font-bold tracking-tight text-text-primary",
  subtitle: "text-base text-text-secondary max-w-2xl",
  actionsWrapper: "flex flex-wrap items-center gap-3 shrink-0 w-full lg:w-auto",
  searchInputWrapper: "relative group min-w-[280px]",
  searchIcon: "absolute inset-y-0 left-3 flex items-center pointer-events-none text-text-secondary group-focus-within:text-primary transition-colors",
  searchInput: "w-full pl-10 pr-4 bg-surface-secondary/50 border border-border rounded-xl focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-all text-sm h-10",
  contentContainer: "min-h-[400px]",
  loaderWrapper: "flex items-center justify-center h-64",
  spinner: "h-8 w-8 animate-spin rounded-full border-b-2 border-primary",
};
