export const notFoundStyles = {
  container: "fixed inset-0 flex items-center justify-center bg-neutral-bg overflow-hidden",
  glowPrimary: "pointer-events-none absolute top-[-10%] left-[-10%] h-[40%] w-[40%] rounded-full bg-primary/5 blur-[100px]",
  glowSecondary: "pointer-events-none absolute bottom-[-10%] right-[-10%] h-[40%] w-[40%] rounded-full bg-blue-500/5 blur-[100px]",
  contentWrapper: "relative z-10 flex w-full max-w-2xl flex-col items-center justify-center p-6 text-center",
  typographyContainer: "relative mb-12",
  bigNumber: "select-none text-[180px] font-black leading-none tracking-tighter text-primary/5 md:text-[240px]",
  cardPositioning: "absolute inset-0 flex items-center justify-center",
  card: "transform rounded-3xl border border-sidebar-border bg-white/90 p-8 shadow-2xl backdrop-blur-md transition-transform duration-500 hover:rotate-0 -rotate-3",
  iconBadge: "mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-2xl bg-primary/10 text-primary",
  cardTitle: "mb-2 text-3xl font-bold text-text-primary",
  cardSubtitle: "italic font-medium text-text-secondary",
  descriptionContainer: "space-y-8",
  descriptionText: "mx-auto max-w-md text-xl text-text-secondary",
  actionsContainer: "flex flex-col items-center justify-center gap-4 sm:flex-row",
  backButton: "h-12 gap-2 rounded-xl border-sidebar-border px-6",
  dashboardButton: "h-12 gap-2 rounded-xl px-10 shadow-lg shadow-primary/20",
  supportText: "mt-16 text-sm text-text-secondary/60",
  supportLink: "font-medium text-primary hover:underline",
};
